# Generated by Django 6.0.6 on 2026-09-11 14:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Layer', 'Layer'), ('Broiler', 'Broiler')], max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('starting_bird_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=10)),
                ('is_seed', models.BooleanField(default=False, help_text='Sample data. Delete before real use.')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EggCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('eggs_collected', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_cracked', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('batch', models.ForeignKey(limit_choices_to={'type': 'Layer'}, on_delete=django.db.models.deletion.CASCADE, related_name='egg_collections', to='tracker.batch')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EggUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, help_text='e.g. home use, given to family', max_length=300)),
                ('batch', models.ForeignKey(limit_choices_to={'type': 'Layer'}, on_delete=django.db.models.deletion.CASCADE, related_name='egg_usages', to='tracker.batch')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('Feed', 'Feed'), ('Medicine', 'Medicine'), ('Equipment', 'Equipment'), ('Labor', 'Labor'), ('Other', 'Other')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, max_length=300)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='tracker.batch')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeedUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_usages', to='tracker.batch')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('type', models.CharField(choices=[('Vaccination', 'Vaccination'), ('Medicine', 'Medicine'), ('Treatment', 'Treatment')], max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('dose_or_quantity', models.CharField(blank=True, max_length=100)),
                ('next_due_date', models.DateField(blank=True, help_text='Only from your vet or the product label.', null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='tracker.batch')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cause', models.CharField(blank=True, max_length=300)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalities', to='tracker.batch')),
            ],
            options={
                'verbose_name_plural': 'mortality records',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('item_type', models.CharField(choices=[('Eggs', 'Eggs'), ('Broiler', 'Broiler')], max_length=10)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='count', max_length=30)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('buyer', models.CharField(blank=True, max_length=200)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='tracker.batch')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BirdMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('type', models.CharField(choices=[('Added', 'Added'), ('Sold', 'Sold'), ('Removed', 'Removed')], max_length=10)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_or_buyer', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='tracker.batch')),
                ('linked_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_movement', to='tracker.sale')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
