# Generated by Django 6.0.6 on 2026-09-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdmovement',
            name='is_seed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eggcollection',
            name='is_seed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eggusage',
            name='is_seed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_seed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedusage',
            name='is_seed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='is_seed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mortality',
            name='is_seed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_seed',
            field=models.BooleanField(default=False),
        ),
    ]
